### ISSUE TITLE
Critical database error

### ISSUE THREAD

**Issue by Unrender** [capsule-corp-ternoa/chain#143]
Hi.

I've got this issue this morning.

`2021-12-12 09:48:48 ✨ Imported #969222 (0x6489…4601)    
2021-12-12 09:48:49 💤 Idle (18 peers), best: #969222 (0x6489…4601), finalized #969220 (0x3e23…a1d6), ⬇ 10.6kiB/s ⬆ 21.0kiB/s    
2021-12-12 09:48:54 ✨ Imported #969223 (0xdd34…520c)    
2021-12-12 09:48:54 💤 Idle (18 peers), best: #969223 (0xdd34…520c), finalized #969220 (0x3e23…a1d6), ⬇ 26.7kiB/s ⬆ 28.5kiB/s    

====================

Version: 0.2.0

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:628:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
   6: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   7: std::panicking::begin_panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
   8: <sp_database::kvdb::DbAdapter<D> as sp_database::Database<H>>::get
   9: <sc_client_db::BlockchainDb<Block> as sp_blockchain::backend::Backend<Block>>::justifications
  10: <sc_service::client::client::Client<B,E,Block,RA> as sc_client_api::client::BlockBackend<Block>>::justifications
  11: sc_network::block_request_handler::BlockRequestHandler<B>::handle_request
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  14: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: std::thread::local::LocalKey<T>::with
  19: tokio::runtime::thread_pool::worker::Context::run_task
  20: tokio::runtime::thread_pool::worker::Context::run
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::thread_pool::worker::run
  23: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  24: tokio::runtime::task::core::CoreStage<T>::poll
  25: tokio::runtime::task::harness::Harness<T,S>::poll
  26: tokio::runtime::blocking::pool::Inner::run
  27: std::sys_common::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/thread.rs:106:17
  30: __pthread_start

Thread 'tokio-runtime-worker' panicked at 'Critical database error: Custom { kind: Other, error: Error { message: "IO error: No such file or directory: While open a file for random read: /tmp/validatornode/chains/ternoa_testnet/db/full/001994.ldb: No such file or directory" } }', /Users/charly/.cargo/git/checkouts/substrate-7e08433d4c370a21/5be50ac/primitives/database/src/kvdb.rs:29

This is a bug. Please report it at:

	https://github.com/capsule-corp-ternoa/chain/issues`

My node is on an iMac running Monterey OS.

**Comment by Unrender** [comment]
Hi Marko,

Have the same issue today : 

`2021-12-17 12:04:54 💤 Idle (22 peers), best: #1042061 (0x5183…6dbe), finalized #1042058 (0xfac2…c903), ⬇ 18.9kiB/s ⬆ 22.2kiB/s    
2021-12-17 12:04:59 💤 Idle (22 peers), best: #1042061 (0x5183…6dbe), finalized #1042059 (0x02e1…f4df), ⬇ 13.1kiB/s ⬆ 22.7kiB/s    
2021-12-17 12:05:01 ✨ Imported #1042062 (0x744c…916d)    

====================

Version: 0.2.0

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:628:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
   6: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   7: std::panicking::begin_panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:460:5
   8: <sp_database::kvdb::DbAdapter<D> as sp_database::Database<H>>::get
   9: sc_client_db::utils::read_header
  10: <sc_client_db::BlockchainDb<Block> as sp_blockchain::backend::HeaderBackend<Block>>::header
  11: <sc_service::client::client::Client<B,E,Block,RA> as sp_blockchain::backend::HeaderBackend<Block>>::header
  12: sc_network::block_request_handler::BlockRequestHandler<B>::handle_request
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: std::thread::local::LocalKey<T>::with
  20: tokio::runtime::thread_pool::worker::Context::run_task
  21: tokio::runtime::thread_pool::worker::Context::run
  22: tokio::macros::scoped_tls::ScopedKey<T>::set
  23: tokio::runtime::thread_pool::worker::run
  24: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  25: tokio::runtime::task::core::CoreStage<T>::poll
  26: tokio::runtime::task::harness::Harness<T,S>::poll
  27: tokio::runtime::blocking::pool::Inner::run
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/thread.rs:106:17
  31: __pthread_start


Thread 'tokio-runtime-worker' panicked at 'Critical database error: Custom { kind: Other, error: Error { message: "IO error: No such file or directory: While open a file for random read: /tmp/validatornode/chains/ternoa_testnet/db/full/001082.ldb: No such file or directory" } }', /Users/charly/.cargo/git/checkouts/substrate-7e08433d4c370a21/5be50ac/primitives/database/src/kvdb.rs:29

This is a bug. Please report it at:

	https://github.com/capsule-corp-ternoa/chain/issues`

Have you an idea ?

**Comment by markopoloparadox** [comment]
Could you change the location where you store your node data? Instead of `--base-path` pointing at the `/tmp/` folder let it point to `~/ternoa/node-data`.

**Comment by Unrender** [comment]
Ok. I'll do that and try to find the new documentation to read changes.
Thank you.

**Comment by Unrender** [comment]
Ok... everything has been working perfectly for 8 days now.
Thank you again.
I close this issue.
