### ISSUE TITLE
Cannot drop a runtime in a context where blocking is not allowed

### ISSUE THREAD

**Issue by bonabovino** [capsule-corp-ternoa/chain#163]
Hi,

I've got this issue today.

2022-01-17 13:18:50 Can't listen on /ip6/::/tcp/30333 because: Other(Custom { kind: Other, error: Other(A(A(A(A(Transport(B(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))))))) })
2022-01-17 13:18:50 Can't listen on /ip4/0.0.0.0/tcp/30333 because: Other(Custom { kind: Other, error: Other(A(A(A(A(Transport(B(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))))))) })
2022-01-17 13:18:50 📦 Highest known block at #0

====================

Version: 0.2.2

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:610:17
   2: std::panicking::begin_panic::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: std::panicking::begin_panic
   5: tokio::runtime::blocking::shutdown::Receiver::wait
   6: tokio::runtime::blocking::pool::BlockingPool::shutdown
   7: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
   8: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  10: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  11: core::iter::adapters::process_results
  12: jsonrpc_http_server::ServerBuilder<M,S>::start_http
  13: sc_rpc_server::inner::start_http
  14: sc_service::start_rpc_servers::{{closure}}
  15: sc_service::start_rpc_servers
  16: sc_service::builder::spawn_tasks
  17: ternoa::service::new_full
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: tokio::park::thread::CachedParkThread::block_on
  20: tokio::runtime::thread_pool::ThreadPool::block_on
  21: sc_cli::runner::Runner<C>::run_node_until_exit
  22: ternoa::command::run
  23: ternoa::main
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: std::rt::lang_start::{{closure}}
  26: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:406:40
      std::panicking::try
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:406:40
      std::panicking::try
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/rt.rs:128:20
  27: main
  28: __libc_start_main
  29: _start

Thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/blocking/shutdown.rs:51

This is a bug. Please report it at:

        https://github.com/capsule-corp-ternoa/chain/issues

**Comment by markopoloparadox** [comment]
Hello,

Have you tried to run two nodes at the same time? Those kinds of error happen when two services are using the same address.

**Comment by bonabovino** [comment]
Hello,

Thank you for your help. I found where the problem came from, I had the moonbeam node on the same server.
Sorry for this inconvenience, I'm a beginner...
